---

# TODO: Split this out into separate handler files, once https://github.com/ansible/ansible/issues/13485 is resolved.


- name: Restart Finder
  command: killall Finder

- name: Restart Dock
  command: killall Dock

- name: Restart Control Strip
  command: killall ControlStrip
  ignore_errors: TRUE

- name: Restart Touch Bar
  command: killall TouchBarAgent
  ignore_errors: TRUE

- name: Restart SystemUIServer
  command: killall SystemUIServer

- name: Reload QuickLook daemon
  command: qlmanage -r

- name: Restart Launch Services
  command: /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -kill -r -domain local -domain system -domain user

# This is required for Bash to find newly added commands.
- name: Rehash
  command: hash -r
