;; Make sure all the cursor keys work from various terminals - including with modifiers.
;; NOTE: We're treating the Alt/Option key as Meta.

; VT100 normal cursor mode.
(define-key input-decode-map "\e[A" [up])
(define-key input-decode-map "\e[B" [down])
(define-key input-decode-map "\e[C" [right])
(define-key input-decode-map "\e[D" [left])
(define-key input-decode-map "\e[F" [end])
(define-key input-decode-map "\e[H" [home])

; VT100 application cursor mode.
(define-key input-decode-map "\eOA" [up])
(define-key input-decode-map "\eOB" [down])
(define-key input-decode-map "\eOC" [right])
(define-key input-decode-map "\eOD" [left])
(define-key input-decode-map "\eOF" [end])
(define-key input-decode-map "\eOH" [home])

(define-key input-decode-map "\e[1~" [home])
(define-key input-decode-map "\e[2~" [insert])
(define-key input-decode-map "\e[3~" [delete])
(define-key input-decode-map "\e[4~" [end])
(define-key input-decode-map "\e[5~" [prior])
(define-key input-decode-map "\e[6~" [next])
(define-key input-decode-map "\e[7~" [home])
(define-key input-decode-map "\e[8~" [end])

(define-key input-decode-map "\e[1;2A" [(shift up)])
(define-key input-decode-map "\e[1;2B" [(shift down)])
(define-key input-decode-map "\e[1;2C" [(shift right)])
(define-key input-decode-map "\e[1;2D" [(shift left)])
(define-key input-decode-map "\e[1;2F" [(shift end)])
(define-key input-decode-map "\e[1;2H" [(shift home)])

(define-key input-decode-map "\e[1;2~" [(shift home)])
(define-key input-decode-map "\e[2;2~" [(shift insert)])
(define-key input-decode-map "\e[3;2~" [(shift delete)])
(define-key input-decode-map "\e[4;2~" [(shift end)])
(define-key input-decode-map "\e[5;2~" [(shift prior)])
(define-key input-decode-map "\e[6;2~" [(shift next)])
(define-key input-decode-map "\e[7;2~" [(shift home)])
(define-key input-decode-map "\e[8;2~" [(shift end)])

(define-key input-decode-map "\e[1;3A" [(meta up)])
(define-key input-decode-map "\e[1;3B" [(meta down)])
(define-key input-decode-map "\e[1;3C" [(meta right)])
(define-key input-decode-map "\e[1;3D" [(meta left)])
(define-key input-decode-map "\e[1;3F" [(meta end)])
(define-key input-decode-map "\e[1;3H" [(meta home)])

(define-key input-decode-map "\e[1;3~" [(meta home)])
(define-key input-decode-map "\e[2;3~" [(meta insert)])
(define-key input-decode-map "\e[3;3~" [(meta delete)])
(define-key input-decode-map "\e[4;3~" [(meta end)])
(define-key input-decode-map "\e[5;3~" [(meta prior)])
(define-key input-decode-map "\e[6;3~" [(meta next)])
(define-key input-decode-map "\e[7;3~" [(meta home)])
(define-key input-decode-map "\e[8;3~" [(meta end)])

(define-key input-decode-map "\e[1;4A" [(shift meta up)])
(define-key input-decode-map "\e[1;4B" [(shift meta down)])
(define-key input-decode-map "\e[1;4C" [(shift meta right)])
(define-key input-decode-map "\e[1;4D" [(shift meta left)])
(define-key input-decode-map "\e[1;4F" [(shift meta end)])
(define-key input-decode-map "\e[1;4H" [(shift meta home)])

(define-key input-decode-map "\e[1;4~" [(shift meta home)])
(define-key input-decode-map "\e[2;4~" [(shift meta insert)])
(define-key input-decode-map "\e[3;4~" [(shift meta delete)])
(define-key input-decode-map "\e[4;4~" [(shift meta end)])
(define-key input-decode-map "\e[5;4~" [(shift meta prior)])
(define-key input-decode-map "\e[6;4~" [(shift meta next)])
(define-key input-decode-map "\e[7;4~" [(shift meta home)])
(define-key input-decode-map "\e[8;4~" [(shift meta end)])

(define-key input-decode-map "\e[1;5A" [(control up)])
(define-key input-decode-map "\e[1;5B" [(control down)])
(define-key input-decode-map "\e[1;5C" [(control right)])
(define-key input-decode-map "\e[1;5D" [(control left)])
(define-key input-decode-map "\e[1;5F" [(control end)])
(define-key input-decode-map "\e[1;5H" [(control home)])

(define-key input-decode-map "\e[1;5~" [(control home)])
(define-key input-decode-map "\e[2;5~" [(control insert)])
(define-key input-decode-map "\e[3;5~" [(control delete)])
(define-key input-decode-map "\e[4;5~" [(control end)])
(define-key input-decode-map "\e[5;5~" [(control prior)])
(define-key input-decode-map "\e[6;5~" [(control next)])
(define-key input-decode-map "\e[7;5~" [(control home)])
(define-key input-decode-map "\e[8;5~" [(control end)])

(define-key input-decode-map "\e[1;6A" [(shift control up)])
(define-key input-decode-map "\e[1;6B" [(shift control down)])
(define-key input-decode-map "\e[1;6C" [(shift control right)])
(define-key input-decode-map "\e[1;6D" [(shift control left)])
(define-key input-decode-map "\e[1;6F" [(shift control end)])
(define-key input-decode-map "\e[1;6H" [(shift control home)])

(define-key input-decode-map "\e[1;6~" [(shift control home)])
(define-key input-decode-map "\e[2;6~" [(shift control insert)])
(define-key input-decode-map "\e[3;6~" [(shift control delete)])
(define-key input-decode-map "\e[4;6~" [(shift control end)])
(define-key input-decode-map "\e[5;6~" [(shift control prior)])
(define-key input-decode-map "\e[6;6~" [(shift control next)])
(define-key input-decode-map "\e[7;6~" [(shift control home)])
(define-key input-decode-map "\e[8;6~" [(shift control end)])

(define-key input-decode-map "\e[1;7A" [(meta control up)])
(define-key input-decode-map "\e[1;7B" [(meta control down)])
(define-key input-decode-map "\e[1;7C" [(meta control right)])
(define-key input-decode-map "\e[1;7D" [(meta control left)])
(define-key input-decode-map "\e[1;7F" [(meta control end)])
(define-key input-decode-map "\e[1;7H" [(meta control home)])

(define-key input-decode-map "\e[1;7~" [(meta control home)])
(define-key input-decode-map "\e[2;7~" [(meta control insert)])
(define-key input-decode-map "\e[3;7~" [(meta control delete)])
(define-key input-decode-map "\e[4;7~" [(meta control end)])
(define-key input-decode-map "\e[5;7~" [(meta control prior)])
(define-key input-decode-map "\e[6;7~" [(meta control next)])
(define-key input-decode-map "\e[7;7~" [(meta control home)])
(define-key input-decode-map "\e[8;7~" [(meta control end)])

(define-key input-decode-map "\e[1;8A" [(shift meta control up)])
(define-key input-decode-map "\e[1;8B" [(shift meta control down)])
(define-key input-decode-map "\e[1;8C" [(shift meta control right)])
(define-key input-decode-map "\e[1;8D" [(shift meta control left)])
(define-key input-decode-map "\e[1;8F" [(shift meta control end)])
(define-key input-decode-map "\e[1;8H" [(shift meta control home)])

(define-key input-decode-map "\e[1;8~" [(shift meta control home)])
(define-key input-decode-map "\e[2;8~" [(shift meta control insert)])
(define-key input-decode-map "\e[3;8~" [(shift meta control delete)])
(define-key input-decode-map "\e[4;8~" [(shift meta control end)])
(define-key input-decode-map "\e[5;8~" [(shift meta control prior)])
(define-key input-decode-map "\e[6;8~" [(shift meta control next)])
(define-key input-decode-map "\e[7;8~" [(shift meta control home)])
(define-key input-decode-map "\e[8;8~" [(shift meta control end)])

(define-key input-decode-map "\e[1;9A" [(meta up)])
(define-key input-decode-map "\e[1;9B" [(meta down)])
(define-key input-decode-map "\e[1;9C" [(meta right)])
(define-key input-decode-map "\e[1;9D" [(meta left)])
(define-key input-decode-map "\e[1;9F" [(meta end)])
(define-key input-decode-map "\e[1;9H" [(meta home)])

(define-key input-decode-map "\e[1;9~" [(meta home)])
(define-key input-decode-map "\e[2;9~" [(meta insert)])
(define-key input-decode-map "\e[3;9~" [(meta delete)])
(define-key input-decode-map "\e[4;9~" [(meta end)])
(define-key input-decode-map "\e[5;9~" [(meta prior)])
(define-key input-decode-map "\e[6;9~" [(meta next)])
(define-key input-decode-map "\e[7;9~" [(meta home)])
(define-key input-decode-map "\e[8;9~" [(meta end)])

(define-key input-decode-map "\e[1;10A" [(shift meta up)])
(define-key input-decode-map "\e[1;10B" [(shift meta down)])
(define-key input-decode-map "\e[1;10C" [(shift meta right)])
(define-key input-decode-map "\e[1;10D" [(shift meta left)])
(define-key input-decode-map "\e[1;10F" [(shift meta end)])
(define-key input-decode-map "\e[1;10H" [(shift meta home)])

(define-key input-decode-map "\e[1;10~" [(shift meta home)])
(define-key input-decode-map "\e[2;10~" [(shift meta insert)])
(define-key input-decode-map "\e[3;10~" [(shift meta delete)])
(define-key input-decode-map "\e[4;10~" [(shift meta end)])
(define-key input-decode-map "\e[5;10~" [(shift meta prior)])
(define-key input-decode-map "\e[6;10~" [(shift meta next)])
(define-key input-decode-map "\e[7;10~" [(shift meta home)])
(define-key input-decode-map "\e[8;10~" [(shift meta end)])
