---

- name: Show Debug menu in App Store app
  osx_defaults:
    domain: com.apple.appstore
    key: ShowDebugMenu
    value: TRUE
    type: bool

# Note that MAS is a 3rd-party app, not something supplied by Apple.
- name: Install Mac App Store command line interface
  homebrew:
    name: mas

- name: Determine if we're signed into Mac App Store
  shell: mas account || true
  register: mas_account
  changed_when: False

- name: Sign into Mac App Store
  shell: "mas signout && mas signin {{ MAS_LOGIN }} {{ MAS_PASSWORD }}"
  when: mas_account.stdout == "Not signed in"

- name: Install apps from App Store
  shell: "echo 'Installing {{ item.name }}' && mas install $(mas search '{{ item.name }}' | grep '\\s*\\d*  {{ item.name }} ' | awk '{ print $1 }')"
  args:
    creates: "/Applications/{{ item.app if item.app is defined else item.name }}.app"
  with_items: "{{ appstore_apps_to_install }}"
