---

- name: Install smcFanControl
  homebrew_cask:
    name: smcfancontrol
  notify:
    - Restart smcFanControl

- name: Get list of configured fan speeds
  shell: defaults read com.eidac.smcFanControl2 Favorites | grep Title | sed -Ee 's/[[:space:]]*Title = "(.*)";/\1/'
  register: configured_fan_speeds
  changed_when: FALSE
  ignore_errors: TRUE

- name: Configure smcFanControl fan speeds
  osx_defaults:
    domain: com.eidac.smcFanControl2
    key: Favorites
    value: [ "<dict><key>Title</key><string>{{ item.name }}</string><key>FanData</key><array><dict><key>Description</key><string>Leftside</string><key>selspeed</key><integer>{{ item.left }}</integer></dict><dict><key>Description</key><string>Rightside</string><key>selspeed</key><integer>{{ item.right }}</integer></dict></array></dict>" ]
    type: array
    array_add: TRUE
  with_items:
    - { name: "Minimum RPM", left: 2160, right: 2000 }
    - { name: "Low RPM", left: 3000, right: 3000 }
    - { name: "Medium RPM", left: 4000, right: 4000 }
    - { name: "High RPM", left: 5000, right: 5000 }
    - { name: "Maximum RPM", left: 5927, right: 5489 }
  when: item.name not in configured_fan_speeds.stdout_lines
  notify:
    - Restart smcFanControl

- name: Configure smcFanControl
  osx_defaults:
    domain: com.eidac.smcFanControl2
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    type: "{{ item.type }}"
  with_items:
    - { key: AutoStart, value: 1, type: int }
    - { key: AutomaticChange, value: 1, type: int }
    - { key: MenuBar, value: 3, type: int }
    - { key: SUCheckAtStartup, value: 1, type: int }
    - { key: SUHasLaunchedBefore, value: 1, type: int }
    - { key: TSensor, value: TC0P, type: string }
    - { key: Unit, value: 1, type: int }            # Show temperatures in Fahrenheit.
    - { key: SelDefault, value: 1, type: int }      # Run at Low RPM by default.
    - { key: selac, value: 2, type: int }           # Run at Medium RPM when on AC.
    - { key: selload, value: 2, type: int }         # Run at Medium RPM when charging.
    - { key: selbatt, value: 1, type: int }         # Run at Low RPM when on battery.
  notify:
    - Restart smcFanControl
