---

- name: Ensure that /usr/local exists and has proper permissions
  file:
    path: /usr/local
    state: directory
    mode: 0755
  become: TRUE

- name: Ensure the Homebrew cache directory exists and has proper permissions
  file:
    path: /Library/Caches/Homebrew
    state: directory
    group: admin
    mode: 0775
  become: TRUE

- name: Install Homebrew
  shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  args:
    creates: /usr/local/bin/brew

- name: Update Homebrew to get latest packages and package updates
  homebrew:
    update_homebrew: yes

- name: Add tap for Homebrew Cask to allow installation of GUI apps
  homebrew_tap:
    tap: caskroom/cask

- name: Add Homebrew taps to allow installation of older versions of packages (like Java)
  homebrew_tap:
    tap:
      - homebrew/cask-versions

- name: Ensure Bash completion directory exists
  file:
    path: "{{ bash_completion_dir }}"
    state: directory

- name: Enable Bash completion for Homebrew commands
  file:
    dest: "{{ bash_completion_dir }}/brew_bash_completion.sh"
    src: /usr/local/Homebrew/completions/bash/brew
    state: link

- name: Install Bash completion for Homebrew Cask
  homebrew:
    name: brew-cask-completion

- name: Add Homebrew taps to allow installation of various fonts
  homebrew_tap:
    tap: "{{ item }}"
  with_items:
    - caskroom/fonts
    - niksy/pljoska

# The Homebrew version of OpenSSL is needed to compile Bundler on El Capitan. See http://adarsh.io/bundler-failing-on-el-capitan/ for details.
- name: Install OpenSSL library on El Capitan
  homebrew:
    name: openssl
  when: ansible_distribution == 'MacOSX' and ansible_distribution_version.startswith('10.11')

- name: See if OpenSSL library is linked
  shell: brew doctor 2>&1 | sed -ne '/You may wish to `brew unlink` these brews:/,$p' | grep openssl
  register: openssl_linked
  ignore_errors: TRUE
  changed_when: FALSE
  when: ansible_distribution == 'MacOSX' and ansible_distribution_version.startswith('10.11')

- name: For linking of OpenSSL library and headers on El Capitan
  homebrew:
    name: openssl
    state: linked
    install_options: force
  when: ansible_distribution == 'MacOSX' and ansible_distribution_version.startswith('10.11') and openssl_linked.rc != 0

- name: Remove any old versions of Homebrew-installed packages
  command: brew cleanup
  changed_when: FALSE
