---

- name: Install Chrome
  homebrew_cask:
    name: google-chrome
    accept_external_apps: TRUE

- name: Add Chrome icon to Dock
  include: add_to_dock.yml
  vars:
    name: Google Chrome
    path: /Applications/Google Chrome.app
    before: Safari

- name: Trust the Chrome download
  command: xattr -dr com.apple.quarantine '/Applications/Google Chrome.app'

# The next time the user starts Chrome, they'll be prompted whether they want to install any new extensions from this list.
- name: Install Chrome Extensions
  copy:
    src: chrome_extension.json
    dest: "{{ ansible_env.HOME }}/Library/Application Support/Google/Chrome/External Extensions/{{ item.value }}.json"
    mode: 0640
  with_items: "{{ chrome_extensions }}"

# Force handlers to run, so Chrome icon is in the dock before we try adding Firefox icon.
- meta: flush_handlers

- name: Install Firefox
  homebrew_cask:
    name: firefox
    accept_external_apps: TRUE

- name: Trust the Firefox download
  command: xattr -dr com.apple.quarantine '/Applications/Firefox.app'

- name: Add Firefox icon to Dock
  include: add_to_dock.yml
  vars:
    name: Firefox
    path: /Applications/Firefox.app
    after: Google Chrome

# Force handlers to run, so Firefox icon is in the dock before we try adding Chromium icon.
- meta: flush_handlers

- name: Install Chromium
  homebrew_cask:
    name: chromium
    accept_external_apps: TRUE

- name: Trust the Chromium download
  command: xattr -dr com.apple.quarantine '/Applications/Chromium.app'

- name: Add Chromium icon to Dock
  include: add_to_dock.yml
  vars:
    name: Chromium
    path: /Applications/Chromium.app
    after: Firefox
