---

- name: Install Ansible
  homebrew:
    name: ansible

- name: Install Vagrant
  homebrew_cask:
    name: vagrant

- name: Determine Vagrant version
  shell: vagrant --version | cut -d ' ' -f 2
  register: vagrant_version
  changed_when: FALSE

- name: Enable Bash completion for Vagrant
  file:
    dest: "{{ bash_completion_dir }}/vagrant_bash_completion.sh"
    src: /opt/vagrant/embedded/gems/{{ vagrant_version.stdout }}/gems/vagrant-{{ vagrant_version.stdout }}/contrib/bash/completion.sh
    state: link

- name: Install VirtualBox
  homebrew_cask:
    name: virtualbox

- name: Install Terraform
  homebrew:
    name: terraform

- name: Install Terraform Inventory
  homebrew:
    name: terraform-inventory
