---

# Install Emacs from Homebrew and Homebrew Cask.
# The Homebrew version no longer supports Cocoa GUI, nor compiling with any options.

- name: Install Emacs TUI
  homebrew:
    name: emacs

- name: Install Emacs GUI
  homebrew_cask:
    name: emacs

- name: Trust the Emacs download
  command: xattr -dr com.apple.quarantine '/Applications/Emacs.app'

# TODO: Make this idempotent.
- name: Use Emacs TUI from CLI
  command: brew link --overwrite emacs

# TODO: Authorize Emacs GUI to run via spctl (Gatekeeper).

- name: Check to see if Emacs icon is already in the Dock
  command: dockutil --find "Emacs"
  register: emacs_dock_icon
  changed_when: FALSE
  ignore_errors: TRUE

- name: Add an icon for Emacs to the Dock
  command: dockutil --add  '/Applications/Emacs.app' --replacing 'Emacs' --after 'Atom'
  when: "'was not found' in emacs_dock_icon.stdout"

# Install Spacemacs into /usr/local, so we can maintain it separately from our Emacs config.
# To enable it, add these 2 lines to your `~/.emacs.d/init.el`:
# ~~~
#    (setq spacemacs-start-directory "/usr/local/share/spacemacs/")
#    (load-file (concat spacemacs-start-directory "init.el"))
# ~~~
- name: Install Spacemacs
  git:
    dest: /usr/local/share/spacemacs
    repo: https://github.com/syl20bnr/spacemacs.git
